# -*- coding: utf-8 -*-
"""flaskTestFile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PesRMbjHA2K0sk1gGN2gghfMroVlJ1DZ
"""

!pip install flask

from flask import Flask
app = Flask(__name__)

@app.route('/')
def home():
   return 'This is Home!'

if __name__ == '__main__':
   app.run('0.0.0.0',port=5000,debug=True)

"""참고 자료 : https://velog.io/@e_juhee/python-Flask"""